const en = {
  details: "Details",
  heat: "Heat",
  smoke: "Smoke",
  loading: "Loading Aegis devices…",
  error: "Unable to load registries",
  retry: "Retry",
  empty: "No Aegis devices found",
  online: "online",
  offline: "offline",
  unknown: "unknown",
  devices: "devices",
  battery: "Battery",
  alarm: "Alarm",
  tamper: "Tamper",
  problem: "Problem",
  bypass: "Bypass",
  update: "Update available",
  lowBattery: "Low battery",
  temperature: "Temperature",
  signal: "Signal",
  other: "Other",
  connectivity: "Connectivity",
  close: "Close",
  cancel: "Cancel",
  confirm: "Confirm",
  bypassAll: "Bypass available devices",
  restoreAll: "Restore available devices",
  restore: "Restore",
  pending: "Sending…",
  disabled: "disabled entities — entity settings",
  noArea: "No area",
  noMatch: "No matching Aegis device. Use an exact device ID or name.",
  ambiguous: "Device name is ambiguous. Use an exact device ID.",
  alarmControl: "Alarm panel",
  clear: "No active alerts",
  elapsed: "elapsed",
  scope: "Available switches",
  changed: "Device scope changed. Review and confirm again.",
  failed: "Some actions failed",
  sent: "Request sent. Waiting for Home Assistant state.",
  deactivation: "Deactivation kinds",
  caution:
    "Bypass may deactivate tamper only or the whole device, depending on integration settings.",
  selection: "Selected devices",
};
const nb: typeof en = {
  details: "Detaljer",
  heat: "Varme",
  smoke: "Røyk",
  loading: "Laster Aegis-enheter…",
  error: "Kunne ikke laste registre",
  retry: "Prøv igjen",
  empty: "Fant ingen Aegis-enheter",
  online: "tilkoblet",
  offline: "frakoblet",
  unknown: "ukjent",
  devices: "enheter",
  battery: "Batteri",
  alarm: "Alarm",
  tamper: "Sabotasje",
  problem: "Problem",
  bypass: "Forbikoble",
  update: "Oppdatering tilgjengelig",
  lowBattery: "Lavt batteri",
  temperature: "Temperatur",
  signal: "Signal",
  other: "Andre",
  connectivity: "Tilkobling",
  close: "Lukk",
  cancel: "Avbryt",
  confirm: "Bekreft",
  bypassAll: "Forbikoble tilgjengelige enheter",
  restoreAll: "Gjenopprett tilgjengelige enheter",
  restore: "Gjenopprett",
  pending: "Sender…",
  disabled: "deaktiverte entiteter — entitetsinnstillinger",
  noArea: "Uten område",
  noMatch: "Ingen Aegis-enhet funnet. Bruk eksakt enhets-ID eller navn.",
  ambiguous: "Enhetsnavnet er ikke entydig. Bruk eksakt enhets-ID.",
  alarmControl: "Alarmpanel",
  clear: "Ingen aktive varsler",
  elapsed: "forløpt",
  scope: "Tilgjengelige brytere",
  changed: "Enhetsutvalget er endret. Kontroller og bekreft på nytt.",
  failed: "Noen handlinger mislyktes",
  sent: "Forespørsel sendt. Venter på tilstand fra Home Assistant.",
  deactivation: "Deaktiveringstyper",
  caution:
    "Forbikobling kan deaktivere bare sabotasje eller hele enheten, avhengig av integrasjonens innstillinger.",
  selection: "Valgte enheter",
};
export type MessageKey = keyof typeof en;
export function localize(
  language: string | undefined,
  key: MessageKey,
  count?: number,
): string {
  const norwegian = /^(nb|no|nn)(-|$)/.test(language ?? "");
  if (count === 1 && key === "devices") return norwegian ? "enhet" : "device";
  if (count === 1 && key === "disabled")
    return norwegian
      ? "deaktivert entitet — entitetsinnstillinger"
      : "disabled entity — entity settings";
  return (norwegian ? nb : en)[key];
}
